apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhdr-dr-cluster-operator-config
  namespace: {{ .Values.job.namespace }}
  labels:
    app.kubernetes.io/name: rhdr-dr-cluster-operator-config
  annotations:
    argocd.argoproj.io/sync-wave: "8"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhdr-dr-cluster-operator-config
  namespace: {{ .Values.configMap.namespace }}
  labels:
    app.kubernetes.io/name: rhdr-dr-cluster-operator-config
  annotations:
    argocd.argoproj.io/sync-wave: "8"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [{{ .Values.configMap.name | quote }}]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhdr-dr-cluster-operator-config
  namespace: {{ .Values.configMap.namespace }}
  labels:
    app.kubernetes.io/name: rhdr-dr-cluster-operator-config
  annotations:
    argocd.argoproj.io/sync-wave: "8"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhdr-dr-cluster-operator-config
subjects:
  - kind: ServiceAccount
    name: rhdr-dr-cluster-operator-config
    namespace: {{ .Values.job.namespace }}
