---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: dell-vm-drpc
  namespace: gitops-vms
  labels:
    cluster.open-cluster-management.io/backup: ramen
spec:
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: dr-policy-15m
  kubeObjectProtection:
    captureInterval: 15m0s
    kubeObjectSelector: {}
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: dell-vm-placement
    namespace: gitops-vms
  preferredCluster: spoke-0
  pvcSelector:
    matchLabels:
      drprotection: "true"
