---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: dell-vm-placement
  namespace: gitops-vms
  annotations:
    cluster.open-cluster-management.io/experimental-scheduling-disable: "true"
spec:
  decisionStrategy:
    groupStrategy:
      clustersPerDecisionGroup: 0
  prioritizerPolicy:
    mode: Additive
  spreadPolicy: {}
